import { StoredUser } from '@/types/auth';
import { DirectoryEmployee, LeaveRequest, PayslipItem } from '@/types/hrms';

export const SEED_USERS: StoredUser[] = [
  {
    user_id: 'usr_1001',
    company_name: 'My Buddy Technologies',
    employee_id: 'ADM-001',
    first_name: 'Sarah',
    last_name: 'Jenkins',
    email: 'sarah.admin@mybuddy.com',
    phone: '9876543210',
    password: 'Admin@12345',
    role: 'HR_ADMIN',
    department: 'People Operations',
    job_title: 'Chief HR Officer',
    joining_date: 'Jan 15, 2024',
  },
  {
    user_id: 'usr_2004',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1042',
    first_name: 'Priya',
    last_name: 'Nair',
    email: 'priya.nair@mybuddy.com',
    phone: '9876543211',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'Product Engineering',
    job_title: 'Software Associate',
    joining_date: 'June 12, 2025',
  },
  {
    user_id: 'usr_2005',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1043',
    first_name: 'Alex',
    last_name: 'Morgan',
    email: 'alex.morgan@mybuddy.com',
    phone: '9876543212',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'UI/UX Design',
    job_title: 'Product Designer',
    joining_date: 'March 01, 2025',
  },
];

export const INITIAL_DIRECTORY: DirectoryEmployee[] = [
  {
    id: '1',
    employee_id: 'EMP-1042',
    name: 'Priya Nair',
    email: 'priya.nair@mybuddy.com',
    role: 'EMPLOYEE',
    department: 'Product Engineering',
    job_title: 'Software Associate',
    status: 'Active',
    joining_date: 'June 12, 2025',
  },
  {
    id: '2',
    employee_id: 'EMP-1043',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@mybuddy.com',
    role: 'EMPLOYEE',
    department: 'Operations',
    job_title: 'Operations Lead',
    status: 'Active',
    joining_date: 'Aug 20, 2024',
  },
  {
    id: '3',
    employee_id: 'EMP-1044',
    name: 'Fatima Ali',
    email: 'fatima.ali@mybuddy.com',
    role: 'EMPLOYEE',
    department: 'Finance',
    job_title: 'Financial Analyst',
    status: 'On leave',
    joining_date: 'Nov 10, 2024',
  },
  {
    id: '4',
    employee_id: 'EMP-1045',
    name: 'Arjun Das',
    email: 'arjun.das@mybuddy.com',
    role: 'EMPLOYEE',
    department: 'Customer Success',
    job_title: 'CS Specialist',
    status: 'Active',
    joining_date: 'Feb 05, 2025',
  },
  {
    id: '5',
    employee_id: 'ADM-001',
    name: 'Sarah Jenkins',
    email: 'sarah.admin@mybuddy.com',
    role: 'HR_ADMIN',
    department: 'People Operations',
    job_title: 'Chief HR Officer',
    status: 'Active',
    joining_date: 'Jan 15, 2024',
  },
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lev_1',
    userId: 'usr_2004',
    userName: 'Priya Nair',
    employeeId: 'EMP-1042',
    type: 'PAID',
    startDate: '2026-08-26',
    endDate: '2026-08-27',
    days: 2,
    reason: 'Family wedding event',
    status: 'PENDING',
    appliedDate: '2026-08-21',
  },
  {
    id: 'lev_2',
    userId: 'usr_2005',
    userName: 'Alex Morgan',
    employeeId: 'EMP-1043',
    type: 'SICK',
    startDate: '2026-08-23',
    endDate: '2026-08-23',
    days: 1,
    reason: 'Dental appointment and recovery',
    status: 'APPROVED',
    appliedDate: '2026-08-20',
  },
];

export const INITIAL_PAYSLIPS: PayslipItem[] = [
  {
    id: 'ps_aug_26',
    month: 'August',
    year: 2026,
    baseSalary: 45000,
    allowances: 7500,
    deductions: 6950,
    netPay: 45550,
    status: 'FINALIZED',
  },
  {
    id: 'ps_jul_26',
    month: 'July',
    year: 2026,
    baseSalary: 45000,
    allowances: 7500,
    deductions: 6300,
    netPay: 46200,
    status: 'FINALIZED',
  },
  {
    id: 'ps_jun_26',
    month: 'June',
    year: 2026,
    baseSalary: 45000,
    allowances: 7000,
    deductions: 6500,
    netPay: 45500,
    status: 'FINALIZED',
  },
];
