import { StoredUser } from '@/types/auth';
import { LeaveRequest, PayslipItem } from '@/types/hrms';

export const SEED_USERS: StoredUser[] = [
  {
    user_id: 'usr_1001',
    company_name: 'My Buddy Technologies',
    employee_id: 'ADM-001',
    first_name: 'Sarah',
    last_name: 'Jenkins',
    name: 'Sarah Jenkins',
    email: 'sarah.admin@mybuddy.com',
    phone: '9876543210',
    password: 'Admin@12345',
    role: 'HR_ADMIN',
    department: 'People Operations',
    job_title: 'Chief HR Officer',
    joining_date: 'Jan 15, 2024',
    attendance_status: 'PRESENT',
  },
  {
    user_id: 'usr_2004',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1042',
    first_name: 'Priya',
    last_name: 'Nair',
    name: 'Priya Nair',
    email: 'priya.nair@mybuddy.com',
    phone: '9876543211',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'Product Engineering',
    job_title: 'Software Associate',
    joining_date: 'Jun 12, 2025',
    attendance_status: 'PRESENT',
  },
  {
    user_id: 'usr_2005',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1043',
    first_name: 'Alex',
    last_name: 'Morgan',
    name: 'Alex Morgan',
    email: 'alex.morgan@mybuddy.com',
    phone: '9876543212',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'UI/UX Design',
    job_title: 'Product Designer',
    joining_date: 'Mar 01, 2025',
    attendance_status: 'ON_LEAVE',
  },
  {
    user_id: 'usr_2006',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1044',
    first_name: 'Rohan',
    last_name: 'Mehta',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@mybuddy.com',
    phone: '9876543213',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'Operations',
    job_title: 'Operations Lead',
    joining_date: 'Aug 20, 2024',
    attendance_status: 'ABSENT',
  },
  {
    user_id: 'usr_2007',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1045',
    first_name: 'Fatima',
    last_name: 'Ali',
    name: 'Fatima Ali',
    email: 'fatima.ali@mybuddy.com',
    phone: '9876543214',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'Finance',
    job_title: 'Financial Analyst',
    joining_date: 'Nov 10, 2024',
    attendance_status: 'ON_LEAVE',
  },
  {
    user_id: 'usr_2008',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1046',
    first_name: 'Arjun',
    last_name: 'Das',
    name: 'Arjun Das',
    email: 'arjun.das@mybuddy.com',
    phone: '9876543215',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'Customer Success',
    job_title: 'CS Specialist',
    joining_date: 'Feb 05, 2025',
    attendance_status: 'PRESENT',
  },
  {
    user_id: 'usr_2009',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1047',
    first_name: 'Neha',
    last_name: 'Sharma',
    name: 'Neha Sharma',
    email: 'neha.sharma@mybuddy.com',
    phone: '9876543216',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'Marketing',
    job_title: 'Growth Analyst',
    joining_date: 'Apr 17, 2025',
    attendance_status: 'ABSENT',
  },
  {
    user_id: 'usr_2010',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1048',
    first_name: 'Vikram',
    last_name: 'Singh',
    name: 'Vikram Singh',
    email: 'vikram.singh@mybuddy.com',
    phone: '9876543217',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'Product Engineering',
    job_title: 'Backend Engineer',
    joining_date: 'Jan 08, 2025',
    attendance_status: 'PRESENT',
  },
  {
    user_id: 'usr_2011',
    company_name: 'My Buddy Technologies',
    employee_id: 'EMP-1049',
    first_name: 'Ananya',
    last_name: 'Kumar',
    name: 'Ananya Kumar',
    email: 'ananya.kumar@mybuddy.com',
    phone: '9876543218',
    password: 'User@12345',
    role: 'EMPLOYEE',
    department: 'UI/UX Design',
    job_title: 'UX Researcher',
    joining_date: 'May 22, 2025',
    attendance_status: 'PRESENT',
  },
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lev_1',
    userId: 'usr_2004',
    userName: 'Priya Nair',
    employeeId: 'EMP-1042',
    type: 'PAID',
    startDate: '2026-08-26',
    endDate: '2026-08-27',
    days: 2,
    reason: 'Family wedding event',
    status: 'PENDING',
    appliedDate: '2026-08-21',
  },
  {
    id: 'lev_2',
    userId: 'usr_2005',
    userName: 'Alex Morgan',
    employeeId: 'EMP-1043',
    type: 'SICK',
    startDate: '2026-08-23',
    endDate: '2026-08-23',
    days: 1,
    reason: 'Dental appointment and recovery',
    status: 'APPROVED',
    appliedDate: '2026-08-20',
  },
  {
    id: 'lev_3',
    userId: 'usr_2007',
    userName: 'Fatima Ali',
    employeeId: 'EMP-1045',
    type: 'PAID',
    startDate: '2026-08-22',
    endDate: '2026-08-24',
    days: 3,
    reason: 'Medical leave',
    status: 'APPROVED',
    appliedDate: '2026-08-19',
  },
];

export const INITIAL_PAYSLIPS: PayslipItem[] = [
  {
    id: 'ps_aug_26',
    month: 'August',
    year: 2026,
    baseSalary: 45000,
    allowances: 7500,
    deductions: 6950,
    netPay: 45550,
    status: 'FINALIZED',
  },
  {
    id: 'ps_jul_26',
    month: 'July',
    year: 2026,
    baseSalary: 45000,
    allowances: 7500,
    deductions: 6300,
    netPay: 46200,
    status: 'FINALIZED',
  },
  {
    id: 'ps_jun_26',
    month: 'June',
    year: 2026,
    baseSalary: 45000,
    allowances: 7000,
    deductions: 6500,
    netPay: 45500,
    status: 'FINALIZED',
  },
];
